name: 'GCP Authentication'
description: 'Authenticates with Google Cloud Platform using Workload Identity Federation'

inputs:
  service_name:
    description: 'Name of the service (used to construct service account email)'
    required: true
  environment:
    description: 'Environment to deploy to (dev/staging/prod)'
    required: false
    default: ''
  prod_project_id:
    description: 'Production GCP project ID'
    required: true
  staging_project_id:
    description: 'Staging GCP project ID'
    required: true
  dev_project_id:
    description: 'Development GCP project ID'
    required: true
  workload_identity_provider:
    description: 'Workload Identity Provider'
    required: true

outputs:
  environment:
    description: "Selected environment (dev/staging/prod)"
    value: ${{ steps.set_env.outputs.env }}
  project_id:
    description: "Selected GCP project ID"
    value: ${{ steps.set_env.outputs.project_id }}

runs:
  using: "composite"
  steps:
    - name: Set environment variables
      id: set_env
      shell: bash
      env:
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
        PROD_GCP_PROJECT_ID: ${{ inputs.prod_project_id }}
        STAGING_GCP_PROJECT_ID: ${{ inputs.staging_project_id }}
        DEV_GCP_PROJECT_ID: ${{ inputs.dev_project_id }}
      run: |
        # Make script executable
        chmod +x ${{ github.action_path }}/scripts/set-environment.sh
        # Run script
        ${{ github.action_path }}/scripts/set-environment.sh

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: "${{ inputs.service_name }}-github@${{ env.PROJECT_ID }}.iam.gserviceaccount.com"
        create_credentials_file: true
        token_format: "access_token"
        audience: "//iam.googleapis.com/${{ inputs.workload_identity_provider }}"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}