name: 'GCP Authentication'
description: 'Authenticates with Google Cloud Platform using Workload Identity Federation'

inputs:
  service_name:
    description: 'Name of the service (used to construct service account email)'
    required: true
  environment:
    description: 'Environment to deploy to (dev/staging/prod)'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Set environment variables
      id: set_env
      shell: bash
      env:
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
        PROD_GCP_PROJECT_ID: ${{ vars.PROD_GCP_PROJECT_ID }}
        STAGING_GCP_PROJECT_ID: ${{ vars.STAGING_GCP_PROJECT_ID }}
        DEV_GCP_PROJECT_ID: ${{ vars.DEV_GCP_PROJECT_ID }}
      run: ${{ github.action_path }}/scripts/set-environment.sh

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: "${{ inputs.service_name }}-github@${{ env.PROJECT_ID }}.iam.gserviceaccount.com"
        create_credentials_file: true
        token_format: "access_token"
        audience: "//iam.googleapis.com/${{ vars.WORKLOAD_IDENTITY_PROVIDER }}"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}