name: 'GCP Secrets'
description: 'Fetches secrets from GCP Secret Manager'

inputs:
  secrets:
    description: 'JSON array of secret names'
    required: true

runs:
  using: "composite"
  steps:
    - name: Fetch secrets
      shell: bash
      run: |
        secrets='${{ inputs.secrets }}'
        for secret in $(echo "$secrets" | jq -r '.[]'); do
          value=$(gcloud secrets versions access latest --secret=$secret)
          echo "${secret^^}_NAME=${value}" >> "$GITHUB_ENV"
        done