name: 'GCP Secrets'
description: 'Fetches secrets from GCP Secret Manager'

inputs:
  service_name:
    description: 'Service name (e.g. "fetch-data-fn")'
    required: true
  secrets:
    description: 'JSON array of secret names (e.g. ["DATA_API_KEY", "DATA_API_URL"])'
    required: true
  secrets_outputs:
    description: 'JSON array of secret outputs (e.g. ["DATA_API_KEY", "DATA_API_URL"])'
    required: true

runs:
  using: "composite"
  steps:
    - name: Fetch secrets
      shell: bash
      run: |
        secrets='${{ inputs.secrets }}'
        secrets_outputs='${{ inputs.secrets_outputs }}'
        readarray -t secret_array < <(echo "$secrets" | jq -r '.[]')
        readarray -t output_array < <(echo "$secrets_outputs" | jq -r '.[]')
        
        for i in "${!secret_array[@]}"; do
          secret="${secret_array[$i]}"
          output_name="${output_array[$i]}"
          value=$(gcloud secrets versions access latest --secret=$secret)
          echo "${output_name}=${value}" >> "$GITHUB_ENV"
        done